// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa9rG_PIZ3aH0a91GdBOac7r9braZ3by8',
    appId: '1:313007468472:web:a95baeb4091b20f583a94d',
    messagingSenderId: '313007468472',
    projectId: 'foodordering-clone-app',
    authDomain: 'foodordering-clone-app.firebaseapp.com',
    storageBucket: 'foodordering-clone-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyK_C4qcf2-SXfWl74N6fhJ0N8NsVrSMw',
    appId: '1:313007468472:android:978fdc688c41134783a94d',
    messagingSenderId: '313007468472',
    projectId: 'foodordering-clone-app',
    storageBucket: 'foodordering-clone-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjWWjSP7RgEmD3vW5NroqdIPOmpBROxoo',
    appId: '1:313007468472:ios:b36e2f5ba62b9e1783a94d',
    messagingSenderId: '313007468472',
    projectId: 'foodordering-clone-app',
    storageBucket: 'foodordering-clone-app.appspot.com',
    iosClientId: '313007468472-ijq4cn4bie2faqg8ujiqou45fjt6eoeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaSellersApp',
  );
}
